[package]
name = "Sefsclienclave"
version = "1.0.0"
authors = ["Antfin"]
edition = "2021"

[lib]
name = "sefsclienclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
log = "=0.4.17"
